[package]
name = "kanidm-auth-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
kanidm_client = "1.4.3"
rpassword = "7.3.1"
tokio = { version = "1.41.1", features = ["rt"] }
