[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0"
]
exceptions = [
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["MPL-2.0"], name = "webpki-roots" },
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "deny"
wildcards = "deny"

deny = [
    "openssl",
    "openssl-sys"
]

skip = []
skip-tree = [
    "thiserror",
    "windows-sys"
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
